//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_health_care
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class e_healthcare_dbEntities : DbContext
    {
        public e_healthcare_dbEntities()
            : base("name=e_healthcare_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAppointment> tblAppointments { get; set; }
        public virtual DbSet<tblAppointmentSlot> tblAppointmentSlots { get; set; }
        public virtual DbSet<tblArea> tblAreas { get; set; }
        public virtual DbSet<tblCancelation> tblCancelations { get; set; }
        public virtual DbSet<tblCharge> tblCharges { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblClinic> tblClinics { get; set; }
        public virtual DbSet<tblDoctor> tblDoctors { get; set; }
        public virtual DbSet<tblDoctorTime> tblDoctorTimes { get; set; }
        public virtual DbSet<tblDoctorType> tblDoctorTypes { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tblMember> tblMembers { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblDiesease> tblDieseases { get; set; }
        public virtual DbSet<tblDonner> tblDonners { get; set; }
        public virtual DbSet<tblVaccine> tblVaccines { get; set; }
        public virtual DbSet<tblEvent> tblEvents { get; set; }
    }
}
