//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_health_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppointment
    {
        public int intAppointmentID { get; set; }
        public Nullable<int> intSlotID { get; set; }
        public Nullable<int> intMemberID { get; set; }
        public string strPatientName { get; set; }
        public Nullable<int> intPatientAge { get; set; }
        public string strPatientGender { get; set; }
        public string strNotes { get; set; }
        public Nullable<bool> blnIsNewCase { get; set; }
        public string strOldCaseNo { get; set; }
        public Nullable<System.DateTime> dtmAppotimentTakenTime { get; set; }
    }
}
