//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_health_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinic
    {
        public int intClinicID { get; set; }
        public string strClinicName { get; set; }
        public Nullable<int> intAreaID { get; set; }
        public string strAddress { get; set; }
        public string strPHoneNo { get; set; }
    }
}
