//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_health_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonner
    {
        public int intDonnerID { get; set; }
        public string strDonnerName { get; set; }
        public Nullable<decimal> decAmount { get; set; }
        public string strNotes { get; set; }
        public Nullable<System.DateTime> dtmDate { get; set; }
    }
}
