//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_health_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        public int intDoctorID { get; set; }
        public Nullable<int> intLoginID { get; set; }
        public string strDoctorName { get; set; }
        public Nullable<int> intTypeID { get; set; }
        public string strDetails { get; set; }
        public string strPhoto { get; set; }
    }
}
