//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_health_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMember
    {
        public int intMemberID { get; set; }
        public Nullable<int> intLoginID { get; set; }
        public string strMemberName { get; set; }
        public Nullable<int> intAge { get; set; }
        public string strAddress { get; set; }
        public string strPhoneNo { get; set; }
        public string strGender { get; set; }
    }
}
