//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_health_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int intPaymentID { get; set; }
        public Nullable<int> intAppoitmentID { get; set; }
        public Nullable<decimal> decAmount { get; set; }
        public string strStatus { get; set; }
    }
}
